---
- name: housekeeping with ansible
  hosts: localhost
  gather_facts: no
  #become: yes
  tasks:
    - name: list all file which want delete
      shell: find {{path}} -mtime +15 -exec ls -l {} \;
      register: hk
      ignore_errors: yes
    - name: list all file which want gzip
      shell: find {{ path }} -mtime -1 ! -iname "*.gz" -exec ls -l {} \;
      register: compres
      ignore_errors: yes
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: compres
    - name: Send notify to Telegram
      community.general.telegram:
        token: '{{token telegram}}'
        api_args:
          chat_id: -{{chatid}}
          parse_mode: "markdown"
          text: "*List yang mau di gzip* \n {{compres.stdout_lines}}"
          #disable_web_page_preview: True
          #disable_notification: True
      when: compres.rc == 0
    - name: execution gzip
      shell: find {{ path }} -mtime -1 -exec gzip -v {} \;
      ignore_errors: yes
    - name: delete execution
      shell: find {{ path }} -mtime +15 -exec rm -vf {} \;
      ignore_errors: yes
